=== josedl4/p1_tds/XML/usuariosUnix.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT System (User*, Group*)>

<!-- Usuario -->
<!ELEMENT User EMPTY>

<!ATTLIST User nombre CDATA #REQUIRED>
<!ATTLIST User passwd CDATA #REQUIRED> 
<!ATTLIST User directorio CDATA #REQUIRED>
<!ATTLIST User uid ID #REQUIRED>
<!ATTLIST User shell (BASH|ASH|CSH|ZSH|KSH|TCSH) "BASH">
<!ATTLIST User nombreCompleto CDATA #IMPLIED>
<!ATTLIST User grupoPrincipal IDREF #REQUIRED>
<!ATTLIST User grupoSecundario IDREFS #IMPLIED>

<!-- Grupo -->
<!ELEMENT Group EMPTY>
<!ATTLIST Group nombre CDATA #REQUIRED>
<!ATTLIST Group idusuarios IDREFS #IMPLIED>
<!ATTLIST Group gid ID #REQUIRED>

=== josedl4/p1_tds/Prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE System SYSTEM "usuariosUnix.dtd">
<System>
    <User nombre="user1" passwd="cotraseña" directorio="HOME" uid="u1" shell="BASH" grupoPrincipal=" g1" grupoSecundario=" g4"/>
    <User nombre="user2" passwd="cotraseña" directorio="HOME" uid="u2" shell="BASH" grupoPrincipal=" g2" grupoSecundario=" g4"/>
    <User nombre="user3" passwd="cotraseña" directorio="HOME" uid="u3" shell="BASH" grupoPrincipal=" g1"/>
    <User nombre="user4" passwd="cotraseña" directorio="HOME" uid="u4" shell="BASH" grupoPrincipal=" g2"/>
    <User nombre="user5" passwd="cotraseña" directorio="HOME" uid="u5" shell="BASH" grupoPrincipal=" g1"/>
    <User nombre="user6" passwd="cotraseña" directorio="HOME" uid="u6" shell="BASH" grupoPrincipal=" g2"/>
    <Group nombre="grupo1" idusuarios=" u1 u3 u5" gid="g1"/>
    <Group nombre="grupo2" idusuarios=" u2 u4 u6" gid="g2"/>
    <Group nombre="grupo3" gid="g3"/>
    <Group nombre="grupo4" idusuarios=" u1 u2" gid="g4"/>
    <Group nombre="ElMejorGrupo" idusuarios=" u1" gid="g1000"/>
</System>

=== josedl4/p1_tds/XML/prueba5_noValida.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE System SYSTEM "usuariosUnix.dtd" >
<System>
  <User nombre='user1' passwd="cotraseña" directorio="HOME" uid="u01" grupoPrincipal="g01" grupoSecundario="g04"/>
  <User nombre="user2" passwd="cotraseña" directorio="HOME" uid="u02" grupoPrincipal="g02" grupoSecundario="g04"/>
  <User nombre="user3" passwd="cotraseña" directorio="HOME" uid="u03" grupoPrincipal="g01"/>
  <User nombre="user4" passwd="cotraseña" directorio="HOME" uid="u04" grupoPrincipal="g02"/>
  <User nombre="user5" passwd="cotraseña" directorio="HOME" uid="u05" grupoPrincipal="g01"/>
  <User nombre="user6" passwd="cotraseña" directorio="HOME" uid="u06" grupoPrincipal="g02"/>	
  
  
  <Group nombre="grupo1" idusuarios="u01 u03 u05" gid="g01"/>
  <Group nombre="grupo2" idusuarios="u02 u04 u07" gid="g02"/>
  <Group nombre="grupo3" gid="g03"/>
  <Group nombre="grupo4" idusuarios="u01 u02" gid="g04"/>
</System>
